### ISSUE TITLE
Custom CSS page isn't working

### ISSUE THREAD

**Issue by chrisrouse** [borkweb/BootstrapMediaWiki#16]
I have $wgSiteCSS = 'bootstrap-mediawiki/custom.css'; in LocalSettings, but my changes added there never seem to show up. Did I miss a step with this?

**Comment by DrLulz** [comment]
I'm having an issue loading anything via "custom.css".

`$wgSiteCSS = 'custom.css';`

Doesn't seem to do anything

**Comment by q2amarket** [comment]
Same issue here. It is not loading `custom.css` in either way. Can you please help to fix it?
