### ISSUE TITLE
includes/SkinTemplate.php require not needed

### ISSUE THREAD

**Issue by filippog** [borkweb/BootstrapMediaWiki#41]
hi,
looks like that newer version of mediawiki don't need skins to require SkinTemplate. I'll actually fail to require the file because it isn't there anymore.

thanks,
filippo

**Comment by acacha** [comment]
I confirm this bug in my wiki (http://acacha.org) with versión 1.24.1

**Comment by acacha** [comment]
See Pull request submitted to solve the problem

**Comment by filippog** [comment]
see pull request https://github.com/borkweb/bootstrap-mediawiki/pull/42
